version: 2
jobs:
  build:
    working_directory: /go/src/github.com/pNagi/go-circleci-docker-kube
    docker:
      - image: circleci/golang:1.9
    environment:
      TEST_RESULTS: /tmp/test-results
      CLOUDSDK_CORE_DISABLE_PROMPTS: 1
    steps:
      - checkout
      - setup_remote_docker
      - run: mkdir -p $TEST_RESULTS
      - run: go get github.com/jstemmer/go-junit-report
      - run:
          name: Run unit tests
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            make test | tee ${TEST_RESULTS}/go-test.out
      - run: make
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output
      - store_test_results:
          path: /tmp/test-results
      - run:
          name: Install gcloud
          command: |
            curl https://sdk.cloud.google.com | bash
      - run:
          name: Auth gcloud
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
            ${HOME}/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
            ${HOME}/google-cloud-sdk/bin/gcloud container clusters get-credentials ${CLUSTERS_NAME} --zone ${CLUSTERS_ZONE} --project ${PROJECT_ID}
      - run: docker build -f Dockerfile -t gcr.io/firsttry-178217/go-circleci-docker-kube:$CIRCLE_SHA1 .
      - deploy:
          name: Deploy Master to GKE
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./deploy.sh
            fi
